user:
  name:
    size: 50
    max_lenght: 255
  mail:
    max_lenght: 50
  pass:
    min_lenght: 8

userhelper:
  gravatar_for:
    size: 80

session:
  remember_me: 1

micropost:
  content:
    max_lenght: 140
  user_size: 50

time_reset: 2

image:
  size: 5
  resize: 500
